### PR TITLE
fix(remove): incomplete removal of packages from apt's database 

### LINKED ISSUE #434: Apt not fully removing package during `cleanup`
**Describe the bug**
When killing the building of a package, apt should remove the dummy, but when running `apt show $name -a`, it still shows up, but goes away when purging it.

**To Reproduce**
Install Pacstall
Install a package, like `blang-git`
Ctrl-C it during building
Run `apt show blang-git -a`

**Expected behavior**
For apt to remove the package completely during `cleanup`.

**Desktop (please complete the following information):**

- OS + version: Debian Sid
- Pacstall Version + branch: 1.7 Develop

### PR DESCRIPTION
**Pull request by Henryws**
## Purpose

Fully remove package when using the `-R` flag.

## Approach

Purge the package in order to remove metadata and the package completely.

## Addendum

Closes #434 

## Checklist

- [x] I confirm that I have read the [contributing guidelines](https://github.com/pacstall/pacstall/blob/develop/CONTRIBUTING.md), and this pull request is abiding by all the clauses stated in the guideline.

### CODE REVIEW

File: misc/scripts/remove.sh [hunk 1]
```diff
@@ -91,7 +91,7 @@ case "$url" in
 		fancy_message info "Removing dummy package"
 		export PACSTALL_REMOVE=1
 
-		if ! sudo --preserve-env=PACSTALL_REMOVE dpkg -r "$name" 2> /dev/null; then
+		if ! sudo --preserve-env=PACSTALL_REMOVE apt purge "$name" 2> /dev/null; then
```
Comment (wizard-28) [inline misc/scripts/remove.sh:94]:
```suggestion
		if ! sudo --preserve-env=PACSTALL_REMOVE apt-get purge "$name" 2> /dev/null; then
```

**Review by wizard-28 — CHANGES_REQUESTED** [review]

**Review by wizard-28 — APPROVED** [review]
Works

**Review by D-Brox — APPROVED** [review]
I suggested this ages ago, for 1.6.1, we should have changed it then...

Anyway, works
