### PR TITLE
Fix: Caching

### LINKED ISSUE #160: Pacstall doesn't redownload scripts
**Describe the bug**
When downloading a pacscript, it won't overwrite the old script in `~/.cache/pacstall/` 

**To Reproduce**
Download a script, wait for an update to the script, and see that it won't overwrite the old file

**Expected behavior**
For it to redownload the script every time pacstall downloads a pacscript

**Desktop (please complete the following information):**

- OS + version: Linux Mint
- Pacstall Version + branch: develop

### PR DESCRIPTION
**Pull request by wizard-28**
# Purpose

Currently the caching in `download.sh` caches pacscripts to  `~/.cache/pacstall`, and it doesn't get cleaned after `install-local.sh` ends 

# Approach

This changes the caching directory to `/tmp/pacstall/pacscripts/`, and cleans it after `install-local` ends

# Progress

- [x] Change caching directory
- [x] Overwrite the file before downloading it
- [x] Change download dir based on `type` 

# Addendum

Fixes #160

### CODE REVIEW

**Review by Henryws — APPROVED** [review]

**Comment by D-Brox** [comment]
Also nuke `.cache/pacstall` if it exists in `update.sh`

File: misc/scripts/install-local.sh [hunk 1]
```diff
@@ -28,6 +28,8 @@ function cleanup () {
 	if [ -f /tmp/pacstall-optdepends ]; then
 		sudo rm /tmp/pacstall-optdepends
 	fi
+
+	rm -rf "/tmp/pacstall/pacscripts/"
```
Comment (D-Brox) [inline misc/scripts/install-local.sh:32]: We already nuke `/tmp/pacstall`, there is no need to nuke it again. It'll just print an error

File: misc/scripts/download.sh [hunk 2]
```diff
@@ -31,8 +31,10 @@ if ! wget -q --tries=10 --timeout=20 --spider https://github.com; then
 fi
 
 if curl --output /dev/null --silent --head --fail "$URL" ; then
-	mkdir -p "$HOME/.cache/pacstall" && cd "$HOME"/.cache/pacstall/
-	mkdir -p "$PACKAGE" && cd "$PACKAGE"
+	if [[ "$type" = "install" ]]; then
+		mkdir -p "/tmp/pacstall/pacscripts/" && cd "/tmp/pacstall/pacscripts/"
+		mkdir -p "$PACKAGE" && cd "$PACKAGE"
```
Comment (D-Brox) [inline misc/scripts/download.sh:36]: I don't think we need to use `mkdir -p "$PACKAGE" && cd "$PACKAGE"` anymore in install

File: misc/scripts/download.sh [hunk 3]
```diff
@@ -31,8 +31,10 @@ if ! wget -q --tries=10 --timeout=20 --spider https://github.com; then
...
+	fi
```
Comment (D-Brox) [inline misc/scripts/download.sh:37]: Needs an `else` for when `$type == "download` to specify where to download the pacscript

**Review by D-Brox — CHANGES_REQUESTED** [review]

File: misc/scripts/install-local.sh (hunk 1 above)
Comment (wizard-28) [reply misc/scripts/install-local.sh:32]: alright, on it.

File: misc/scripts/download.sh (hunk 2 above)
Comment (wizard-28) [reply misc/scripts/download.sh:36]: why?

File: misc/scripts/download.sh (hunk 3 above)
Comment (wizard-28) [reply misc/scripts/download.sh:37]: @Henryws says when `-D` flag is active, then just download it in `pwd`, so not specifying an `else` will automatically download it in `pwd`

File: misc/scripts/download.sh (hunk 2 above)
Comment (D-Brox) [reply misc/scripts/download.sh:36]: Because of how we source the pacscript, it doesn't matter where it is, only that we are in the right dir

Comment (wizard-28) [reply misc/scripts/download.sh:36]: Alright, you know the best! On it.

File: misc/scripts/download.sh (hunk 3 above)
Comment (D-Brox) [reply misc/scripts/download.sh:36]: Ok

**Review by D-Brox — APPROVED** [review]

**Review by NarutoXY — APPROVED** [review]
