### PR TITLE
fix(install-local): force git clones on `-git`

### LINKED ISSUE #509: Pacstall doesn't force git clones on `-git`
Pacstall doesn't force git clones on `-git` packages, therefore `-git` pacscripts cloning from sourcehut don't work, as pacstall currently used `.git` suffix to determine a git clone (which the sourcehut URLs don't have).

### PR DESCRIPTION
**Pull request by wizard-28**
## Purpose

Fixes #509

## Approach

Check if the `name` ends with `-git`, then git clone, otherwise proceed with the usual `url` based operations.

## Checklist

- [x] I confirm that I have read the [contributing guidelines](https://github.com/pacstall/pacstall/blob/develop/CONTRIBUTING.md), and this pull request is abiding by all the clauses stated in the guideline.

### CODE REVIEW

File: misc/scripts/install-local.sh [hunk 1]
```diff
@@ -444,77 +443,78 @@ fi
...
 			fi
-
-			fancy_message info "Storing pacscript"
-			sudo mkdir -p /var/cache/pacstall/"$PACKAGE"/"$version"
-			if ! cd "$DIR" 2> /dev/null; then
-				error_log 1 "install $PACKAGE"; fancy_message error "Could not enter into ${DIR}"; exit 1
+			# unzip file
+			unzip -q "${url##*/}" 1>&1 2>/dev/null
+			# cd into it
+			cd ./*/ 2> /dev/null || ( error_log 1 "install $PACKAGE"; fancy_message warn "Could not enter into the downloaded archive" )
```
Comment (Henryws) [inline misc/scripts/install-local.sh:464]:
```suggestion
			cd ./*/ 2> /dev/null || { error_log 1 "install $PACKAGE"; fancy_message warn "Could not enter into the downloaded archive"; }
```

File: misc/scripts/install-local.sh [hunk 2]
```diff
@@ -444,77 +443,78 @@ fi
...
+			fi
+		;;
+		*)
+			download "$url"
+			# I think you get it by now
+			if ! hashcheck "${url##*/}"; then
+				return 1
+			fi
+			tar -xf "${url##*/}" 1>&1 2>/dev/null
+			cd ./*/ 2> /dev/null || ( error_log 1 "install $PACKAGE"; fancy_message warn "Could not enter into the downloaded archive" )
```
Comment (Henryws) [inline misc/scripts/install-local.sh:514]:
```suggestion
			cd ./*/ 2> /dev/null || { error_log 1 "install $PACKAGE"; fancy_message warn "Could not enter into the downloaded archive"; }
```

**Review by Henryws — CHANGES_REQUESTED** [review]
Replace subshells with brackets.

File: misc/scripts/install-local.sh (hunk 1 above)
Comment (wizard-28) [reply misc/scripts/install-local.sh:464]: Unrelated tho

File: misc/scripts/install-local.sh (hunk 2 above)
Comment (wizard-28) [reply misc/scripts/install-local.sh:514]: Unrelated tho

Comment (wizard-28) [reply misc/scripts/install-local.sh:514]: Unrelated tho

**Review by Henryws — CHANGES_REQUESTED** [review]
`cp` error
```
[+] INFO: Building
[+] INFO: Installing
cp: cannot create directory '/usr/src/pacstall/lyrebird-git/usr/share/lyrebird': No such file or directory
[+] INFO: Symlinking files
[+] INFO: Storing pacscript
[+] INFO: Cleaning up
```
Does not happen on the develop branch

**Comment by wizard-28** [comment]
@Henryws what to do with this? In Discord you confirmed that this works perfectly...

**Comment by wizard-28** [comment]
@Henryws

File: misc/scripts/install-local.sh [hunk 3]
```diff
@@ -444,77 +443,78 @@ fi
...
-				if ! postinst; then
-					error_log 5 "postinst hook"
-					fancy_message error "Could not run postinst hook successfully"
-					exit 1
-				fi
+if [[ "$name" == *-git ]]; then
+	# git clone quietly, with no history, and if submodules are there, download with 10 jobs
+	git clone --quiet --depth=1 --jobs=10 "$url"
+	# cd into the directory
+	cd ./*/ 2> /dev/null || ( error_log 1 "install $PACKAGE"; fancy_message warn "Could not enter into the cloned git repository" )
```
Comment (Henryws) [inline misc/scripts/install-local.sh:450]: Exit if this fails

**Review by Henryws — CHANGES_REQUESTED** [review]

File: misc/scripts/install-local.sh (hunk 3 above)
Comment (wizard-28) [reply misc/scripts/install-local.sh:450]: Suggest

Comment (Henryws) [inline misc/scripts/install-local.sh:450]:
```suggestion
	cd ./*/ 2> /dev/null || ( error_log 1 "install $PACKAGE"; fancy_message warn "Could not enter into the cloned git repository"; cleanup; exit 1 )
```

**Review by Henryws — CHANGES_REQUESTED** [review]

File: misc/scripts/install-local.sh [hunk 4]
```diff
@@ -444,77 +443,78 @@ fi
...
-				if ! postinst; then
-					error_log 5 "postinst hook"
-					fancy_message error "Could not run postinst hook successfully"
-					exit 1
-				fi
+if [[ "$name" == *-git ]]; then
+	# git clone quietly, with no history, and if submodules are there, download with 10 jobs
+	git clone --quiet --depth=1 --jobs=10 "$url"
+	# cd into the directory
+	cd ./*/ 2> /dev/null || ( error_log 1 "install $PACKAGE"; fancy_message warn "Could not enter into the cloned git repository"; cleanup; exit 1 )
```
Comment (Henryws) [inline misc/scripts/install-local.sh:450]: Turns out you cannot exit from a subshell, so change this to brackets instead.

File: misc/scripts/install-local.sh [hunk 5]
```diff
@@ -444,77 +443,78 @@ fi
...
 			fi
-
-			fancy_message info "Storing pacscript"
-			sudo mkdir -p /var/cache/pacstall/"$PACKAGE"/"$version"
-			if ! cd "$DIR" 2> /dev/null; then
-				error_log 1 "install $PACKAGE"; fancy_message error "Could not enter into ${DIR}"; exit 1
+			# unzip file
+			unzip -q "${url##*/}" 1>&1 2>/dev/null
+			# cd into it
+			cd ./*/ 2> /dev/null || ( error_log 1 "install $PACKAGE"; fancy_message warn "Could not enter into the downloaded archive" )
```
Comment (Henryws) [inline misc/scripts/install-local.sh:464]: Same here

File: misc/scripts/install-local.sh [hunk 6]
```diff
@@ -444,77 +443,78 @@ fi
...
+			fi
+		;;
+		*)
+			download "$url"
+			# I think you get it by now
+			if ! hashcheck "${url##*/}"; then
+				return 1
+			fi
+			tar -xf "${url##*/}" 1>&1 2>/dev/null
+			cd ./*/ 2> /dev/null || ( error_log 1 "install $PACKAGE"; fancy_message warn "Could not enter into the downloaded archive" )
```
Comment (Henryws) [inline misc/scripts/install-local.sh:514]: Same here

**Review by Henryws — CHANGES_REQUESTED** [review]

**Comment by wizard-28** [comment]
@Henryws resolve the merge conflict.

File: misc/scripts/install-local.sh [hunk 7]
```diff
@@ -444,77 +443,78 @@ fi
...
-				if ! postinst; then
-					error_log 5 "postinst hook"
-					fancy_message error "Could not run postinst hook successfully"
-					exit 1
-				fi
+if [[ "$name" == *-git ]]; then
+	# git clone quietly, with no history, and if submodules are there, download with 10 jobs
+	git clone --quiet --depth=1 --jobs=10 "$url"
+	# cd into the directory
+	cd ./*/ 2> /dev/null || { error_log 1 "install $PACKAGE"; fancy_message warn "Could not enter into the cloned git repository"; cleanup; exit 1; }
```
Comment (Henryws) [inline misc/scripts/install-local.sh:450]: Mention that Pacstall is going to clean up.

File: misc/scripts/install-local.sh [hunk 8]
```diff
@@ -444,77 +443,78 @@ fi
...
 			fi
-
-			fancy_message info "Storing pacscript"
-			sudo mkdir -p /var/cache/pacstall/"$PACKAGE"/"$version"
-			if ! cd "$DIR" 2> /dev/null; then
-				error_log 1 "install $PACKAGE"; fancy_message error "Could not enter into ${DIR}"; exit 1
+			# unzip file
+			unzip -q "${url##*/}" 1>&1 2>/dev/null
+			# cd into it
+			cd ./*/ 2> /dev/null || { error_log 1 "install $PACKAGE"; fancy_message warn "Could not enter into the downloaded archive"; }
```
Comment (Henryws) [inline misc/scripts/install-local.sh:464]: Add cleanup here.

File: misc/scripts/install-local.sh [hunk 9]
```diff
@@ -444,77 +443,78 @@ fi
...
+			fi
+		;;
+		*)
+			download "$url"
+			# I think you get it by now
+			if ! hashcheck "${url##*/}"; then
+				return 1
+			fi
+			tar -xf "${url##*/}" 1>&1 2>/dev/null
+			cd ./*/ 2> /dev/null || { error_log 1 "install $PACKAGE"; fancy_message warn "Could not enter into the downloaded archive"; }
```
Comment (Henryws) [inline misc/scripts/install-local.sh:514]: Add cleanup here.

**Review by Henryws — CHANGES_REQUESTED** [review]

File: misc/scripts/install-local.sh (hunk 9 above)
Comment (wizard-28) [reply misc/scripts/install-local.sh:520]: Invalid

**Comment by wizard-28** [comment]
@Henryws

**Review by D-Brox — APPROVED** [review]

File: misc/scripts/install-local.sh (hunk 9 above)
Comment (D-Brox) [reply misc/scripts/install-local.sh:520]: Invalid, since it's not always an achive. We didn't even need to log as error, it's just a warning

File: misc/scripts/install-local.sh [hunk 10]
```diff
@@ -450,94 +449,84 @@ if [[ -n $patch ]]; then
...
+	}
+	# Check the integrity
+	git fsck --full
+else
+	case "$url" in
+		*.zip)
+			download "$url"
+			# hash the file
+			if ! hashcheck "${url##*/}"; then
+				exit 1
```
Comment (Henryws) [inline misc/scripts/install-local.sh:471]:
```suggestion
				return 1
```

**Review by Henryws — CHANGES_REQUESTED** [review]

**Review by Henryws — APPROVED** [review]
