### PR TITLE
fix: install pacdeps from the same origin

### LINKED ISSUE #680: Installing item with multiple repositories, dependencies defaults to default repo
### Describe the bug

Installing the `linux-kernel` package from https://github.com/rhino-linux/repo has dependencies default to the default Pacstall repository, which is a patch behind. Therefore it's installing the 6.0 Linux kernel instead of 6.0.1

### To reproduce

Add the Rhino Linux repository: `pacstall -A https://raw.githubusercontent.com/rhino-linux/repo/master`

Install linux-kernel `pacstall -I linux-kernel`

Choose to install via rhino-linux/repo

### Expected behavior

Installs dependencies via `rhino-linux` repository

### Screenshots

image

### OS version

Ubuntu 22.04

### Pacstall version

2.0.1 Mellow

### PR DESCRIPTION
**Pull request by D-Brox**
## Purpose

Currently, pacdeps are being installed from the main repo if they exist there instead of giving preference to the same repo as the package being installed

## Approach

Check if the pacdep exists in the same repo as the package that requires it and install from it if it exists

## Addendum

Closes #680

## Checklist

- [x] I confirm that I have read the [contributing guidelines](https://github.com/pacstall/pacstall/blob/develop/CONTRIBUTING.md), and this pull request is abiding by all the clauses stated in the guideline.

### CODE REVIEW

File: misc/scripts/install-local.sh [hunk 1]
```diff
@@ -800,6 +800,9 @@ if [[ -n $pacdeps ]]; then
         touch "/tmp/pacstall-pacdeps-$i"
 
         [[ $KEEP ]] && cmd="-KPI" || cmd="-PI"
+        if pacstall -S "${i}@${REPO}"; then
```
Comment (Elsie19) [inline misc/scripts/install-local.sh:803]: This should be redirecting output.

**Review by Elsie19 — CHANGES_REQUESTED** [review]

File: misc/scripts/install-local.sh (hunk 1 above)
Comment (D-Brox) [reply misc/scripts/install-local.sh:803]: Oh, I forgot

File: misc/scripts/install-local.sh [hunk 2]
```diff
@@ -800,6 +800,9 @@ if [[ -n $pacdeps ]]; then
         touch "/tmp/pacstall-pacdeps-$i"
 
         [[ $KEEP ]] && cmd="-KPI" || cmd="-PI"
+        if pacstall -S "${i}@${REPO}" 2&>/dev/null; then
```
Comment (Elsie19) [inline misc/scripts/install-local.sh:803]:
```suggestion
        if pacstall -S "${i}@${REPO}" &>/dev/null; then
```

**Review by Elsie19 — CHANGES_REQUESTED** [review]

**Review by Elsie19 — APPROVED** [review]
