### PR TITLE
fix(log): figure out what `gives` is based on Deb

### LINKED ISSUE #736: `*-deb` packages do not uninstall when `gives` is not present
### Describe the bug

`*-deb` pacscripts that don't include the `gives` argument do not uninstall.

### To reproduce

install any package that does not have the `gives` argument in the pacscript, e.g. `github-desktop-deb`.

### Expected behavior

the installed package can be uninstalled.

### Screenshots

pacstall-deb

### OS version

Kubuntu 22.10

### Pacstall version

3.0.2 Picotee

### PR DESCRIPTION
**Pull request by Henryws**
## Purpose

`gives` is needed on Debs to get the actual apt package name. If it does not exist, Pacstall will try to remove debs with the apt name `name`, which most definitely is not the canonical name. 

## Approach

Figure out the package name anyways and warn the user.

## Addendum

Fixes #736 

## Checklist

- [x] I confirm that I have read the [contributing guidelines](https://github.com/pacstall/pacstall/blob/develop/CONTRIBUTING.md), and this pull request is abiding by all the clauses stated in the guideline.

### CODE REVIEW

**Review by wizard-28 — APPROVED** [review]

**Review by D-Brox — APPROVED** [review]

File: misc/scripts/install-local.sh [hunk 1]
```diff
@@ -110,7 +113,9 @@ function log() {
         if [[ -n $ppa ]]; then
             echo "_ppa=\"$ppa"\"
         fi
-        if [[ -n $gives ]]; then
+        if [[ $name == *-deb ]] && [[ -z $gives ]]; then
+            echo "_gives=\"$(dpkg -f ./"${url##*/}" | sed -n "s/^Package: //p")"\"
```
Comment (D-Brox) [inline misc/scripts/install-local.sh:117]:
```suggestion
            echo "_gives=\"$(dpkg -f ./"${url##*/}" | sed -n "s/^Package: //p" |cut -d" " -f2)"\"
```

**Review by D-Brox — CHANGES_REQUESTED** [review]
~`_gives="Package: name"`~

**Review by D-Brox — APPROVED** [review]
