### PR TITLE
fix: `-K` flag on pacdep fails (keep build dir)

### LINKED ISSUE #373: Error on pacdeps keep
**Describe the bug**
When Pacstall's pacdeps fail to install, it cleans up

**To Reproduce**
Install Pacstall
Update to develop
Install Soundux, make pipewire install fail
Notice that it cleans it up, when it shouldn't

**Expected behavior**
For it to leave everything intact

**Screenshots**
image

**Desktop (please complete the following information):**

- OS + version: Debian Sid
- Pacstall Version + branch:1.6.2 Develop

### PR DESCRIPTION
**Pull request by D-Brox**
## Purpose

Keep build dir files of pacdeps when installation fails

## Addendum

Closes #373

## Checklist

- [x] I confirm that I have read the [contributing guidelines](https://github.com/pacstall/pacstall/blob/develop/CONTRIBUTING.md), and this pull request is abiding by all the clauses stated in the guideline.

### CODE REVIEW

File: misc/scripts/install-local.sh [hunk 1]
```diff
@@ -312,8 +312,8 @@ if [[ -n "$pacdeps" ]]; then
 		# If /tmp/pacstall-pacdeps-"$i" is available, it will trigger the logger to log it as a dependency
 		sudo touch /tmp/pacstall-pacdeps-"$i"
 		
-		[[ $KEEP ]] && k="-K"
-		if ! pacstall -P "$k" -I "$i"; then
+		[[ $KEEP ]] && cmd="-KPI" || cmd="-PI"
+		if ! pacstall "$cmd" "$i"; then
```
Comment (wizard-28) [inline misc/scripts/install-local.sh]: What does this do?

Comment (D-Brox) [reply misc/scripts/install-local.sh]: Allows us to run the pacdep install with the keep flag

**Review by Henryws — APPROVED** [review]
