### PR TITLE
fix(install-local): error out if optdepends has no description

### LINKED ISSUE #507: pacstall skips the last letter of the last dependency specified in the `optdepends` list
**Describe the bug**

`pacstall` seems to skip the last letter of the last dependency specified in the `optdepends` list.

For example, for the following `optdepends`

```
optdepends=( "sqlite3" "libsynctex-dev" "libseccomp-dev" "libmagic-dev" )
```

I get the following output:

```
[+] INFO: zathura has optional dependencies that can enhance its functionalities
Optional dependencies:
    sqlite3
    libsynctex-dev
    libseccomp-dev
    libmagic-dev     <----- Here it's fine.
Do you want to install them [Y/n]
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'zathura' instead of '/tmp/pacstall/zathura-pacstall.deb'
The following packages were automatically installed and are no longer required:
  libgit2-28 libhttp-parser2.9 libjsoncpp1 libmbedcrypto3 libmbedtls12 libmbedx509-0 librhash0 libutempter0
Use 'sudo apt autoremove' to remove them.
Suggested packages:
  libsynctex-dev libseccomp-dev libmagic-de    <------------------------ should have been libmagic-dev
The following NEW packages will be installed:
  zathura
```

**To Reproduce**

You can run pacsatll using the following recipe file. You 'll see what I've described above during the suggested dependencies step.

```
name="zathura"
url="https://github.com/pwmt/zathura.git"
description="zathura - a document viewer"
breaks="zathura zathura-deb"
gives="zathura"
pkgver() {
  git ls-remote "${url}" master | cut -f1
}
version="$(pkgver)"
maintainer="bergercookie <nickkouk@gmail.com>"
build_depends="meson gettext librsvg2-bin python3-sphinx doxygen python3-breathe python3-sphinx-rtd-theme"
depends="libgtk-3-dev libglib2.0-dev libgirara-dev libgirara-gtk3-3"
optdepends=( "sqlite3" "libsynctex-dev" "libseccomp-dev" "libmagic-dev" )

prepare() {
  true
}

build() {
  meson --prefix "$STOWDIR/$name" build
  cd build
  ninja
}

install() {
  sudo ninja install
}
```

**Desktop (please complete the following information):**

- OS + version: Ubuntu 20.04
- Pacstall Version + branch: 1.7.2 Carmine

### PR DESCRIPTION
**Pull request by Henryws**
## Purpose

Fail if `optdepends` key's do not have a description, and cut to correct character.

## Approach

Check the keys with a for loop.

## Addendum

Fixes #507

## Checklist

- [x] I confirm that I have read the [contributing guidelines](https://github.com/pacstall/pacstall/blob/develop/CONTRIBUTING.md), and this pull request is abiding by all the clauses stated in the guideline.

### CODE REVIEW

File: misc/scripts/install-local.sh [hunk 1]
```diff
@@ -178,7 +178,14 @@ function makeVirtualDeb {
 		fi
 
 		printf "Suggests:" |sudo tee -a "$SRCDIR/$name-pacstall/DEBIAN/control" > /dev/null
-		printf " %s\n" "${optdepends[@]}" | awk -F': ' '{print $1}' | tr '\n' ',' | head -c -2 | sudo tee -a "$SRCDIR/$name-pacstall/DEBIAN/control" > /dev/null
+		for i in "${optdepends[@]}"; do
+			if ! grep -q ':' <<< "${i}"; then
+				fancy_message error "${i} does not have a description"
```
Comment (D-Brox) [inline misc/scripts/install-local.sh:183]: Should we error out or just add warning and rework the splitting method?

File: misc/scripts/install-local.sh [hunk 2]
```diff
@@ -178,7 +178,14 @@ function makeVirtualDeb {
...
+				cleanup
+				return 1
+			fi
+		done
+		printf " %s\n" "${optdepends[@]}" | awk -F': ' '{print $1}' | tr '\n' ',' | head -c -1 | sudo tee -a "$SRCDIR/$name-pacstall/DEBIAN/control" > /dev/null
```
Comment (D-Brox) [inline misc/scripts/install-local.sh:188]: Is it  `head -c -1` or `had -c -2`?

Comment (Henryws) [reply misc/scripts/install-local.sh:188]: `head -c -1`

File: misc/scripts/install-local.sh (hunk 1 above)
Comment (Henryws) [reply misc/scripts/install-local.sh:183]: Well, `optdepends` is supposed to be supplemental packages, so it might not immediately make sense why a package is being suggested, without a description.

**Review by D-Brox — APPROVED** [review]

**Review by wizard-28 — APPROVED** [review]
